// Movie Now Playing
export const CLEAR_MOVIE_NOW_PLAYING_LIST = 'CLEAR_MOVIE_NOW_PLAYING_LIST';
export const SET_MOVIE_NOW_PLAYING_LIST = 'SET_MOVIE_NOW_PLAYING_LIST';

// Movie Coming Soon
export const CLEAR_MOVIE_COMING_SOON_LIST = 'CLEAR_MOVIE_COMING_SOON_LIST';
export const SET_MOVIE_COMING_SOON_LIST = 'SET_MOVIE_COMING_SOON_LIST';

// Movie Trending
export const CLEAR_MOVIE_TRENDING_LIST = 'CLEAR_MOVIE_TRENDING_LIST';
export const SET_MOVIE_TRENDING_LIST = 'SET_MOVIE_TRENDING_LIST';

// Movie Details
export const CLEAR_MOVIE_DETAILS_LIST = 'CLEAR_MOVIE_DETAILS_LIST';
export const SET_MOVIE_DETAILS_LIST = 'SET_MOVIE_DETAILS_LIST';

// Favorite Movie
export const SET_FAVORITE_MOVIE_LIST = 'SET_FAVORITE_MOVIE_LIST';
export const CLEAR_FAVORITE_MOVIE_LIST = 'CLEAR_FAVORITE_MOVIE_LIST';
export const UPDATE_FAVORITE_MOVIE_LIST = 'UPDATE_FAVORITE_MOVIE_LIST';
export const DELETE_FAVORITE_MOVIE_LIST = 'DELETE_FAVORITE_MOVIE_LIST';
